site_name: Monte Jones
theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search
